kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-dep
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: zorochan/node-app
          ports:
            - containerPort: 8000
      

