kind: Job
apiVersion: v1

metadata:
  name: todo-job
  namespace: todo-app

spec:
  template:
    spec:
      containers:
        - name: my-job
          image: busybox
          command: ["echo" , "hello"]
      restartPolicy: Never      
